language: ruby

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - 2.4.0-rc1
  - ruby-head
  - rbx

gemfile:
 - Gemfile

branches:
  only:
    - master

before_install: gem update bundler
script: bundle exec rake test

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
