language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.3
  - 2.3.0
  - ruby-head
  - rbx

gemfile:
 - Gemfile

branches:
  only:
    - master

before_install: gem update bundler
script: bundle exec rake test

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
